### PR TITLE
Main

### PR DESCRIPTION
**Pull request by AbrahamAjuelos**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by mishalp-crest** [comment]
@AbrahamAjuelos 
Can you push all the changes in this [PR](https://github.com/splunk-soar-connectors/darktrace/pull/2) 
so that we can maintain everything in one PR

**Comment by mishalp-crest** [comment]
@AbrahamAjuelos
Can you push all the changes in this https://github.com/splunk-soar-connectors/darktrace/pull/2
so that we can maintain everything in one PR
or else you can give me write access to your repository so that I can push the required standard changes

**Comment by AbrahamAjuelos** [comment]
> 
@mishalp-crest 
I've had to create a new pull request to update the content on the Feature branch. Feature should be updated with latest content after merging #5. Can you merge it?

**Comment by mishalp-crest** [comment]
@AbrahamAjuelos It's merged now.
Kindly resolve other discussed failures too.
so that I can take this further

**Comment by AbrahamAjuelos** [comment]
@mishalp-crest 

Before we merge into Feature again I will keep this PR open to check test progress.

Remaining tests you can fix for us:

1. verbose_periods
2. sequential_order
3. repo_name_has_expected_app_id
4. minimal_data_paths 
5. min_platform_version

Remaining tests for us to fix:

1. min_number_log_statements: I have added more log statements but we still have the same issue:

image

Can you explain why this test still fails?

Thanks in advance.

**Comment by mishalp-crest** [comment]
@AbrahamAjuelos 
For min_number_log_statements you can refer [digitalshadows connector file](https://github.com/splunk-soar-connectors/digitalshadows/pull/2/files#diff-bead98343fbbaf3c519e806bca093fd56ef379f6e24db4e472791d17e7dd0716R116) or [cybereason connector file](https://github.com/splunk-soar-connectors/cybereason/pull/7/commits/617cc2f0931f1c68572bac364e4dbb8a68775a65)

The pipeline is unable to detect the required logs due to the class-based structure 
above apps have a similar kind of class-based structure and a pipeline is passing for them
you can do a similar kind of fix

**Comment by mishalp-crest** [comment]
@AbrahamAjuelos 
Can you keep this branch in sync with feature branch?

**Comment by AbrahamAjuelos** [comment]
@mishalp-crest 
Is this test passing for those apps because the class inherits from BaseConnector or because the file is located in the root directory?

**Comment by mishalp-crest** [comment]
> @mishalp-crest Is this test passing for those apps because the class inherits from BaseConnector or because the file is located in the root directory?

The pipeline is expecting all the expected functions' names in the connector file only.
That's why it is working for both apps.
Basically, you have to put the expected functions and log statements in the connector file to pass the pipeline.
so, can you please do the changes accordingly?

**Comment by AbrahamAjuelos** [comment]
@mishalp-crest we have followed a code structure that was previously agreed on with your engineering team to improve maintainability and the visual aspect of the code. Pushing all functions back to a unique file makes the readability and structure of the code not ideal. Would it be possible for your pipeline test to check on subdirectories?

**Comment by mishalp-crest** [comment]
> @AbrahamAjuelos For min_number_log_statements you can refer [digitalshadows connector file](https://github.com/splunk-soar-connectors/digitalshadows/pull/2/files#diff-bead98343fbbaf3c519e806bca093fd56ef379f6e24db4e472791d17e7dd0716R116) or [cybereason connector file](https://github.com/splunk-soar-connectors/cybereason/pull/7/commits/617cc2f0931f1c68572bac364e4dbb8a68775a65)
> 
> The pipeline is unable to detect the required logs due to the class-based structure above apps have a similar kind of class-based structure and a pipeline is passing for them you can do a similar kind of fix


@AbrahamAjuelos 
Would it be possible for you to follow the above suggested workaround? 

Also,  will discuss  the possibility of checking the subdirectories with the team

**Comment by mishalp-crest** [comment]
App code is in next hence, closing this

**Pull request closed without merging**
